version: '2'

services:
  flux1:
    build: ./cmd/fluxd
    hostname: flux1
    entrypoint: fluxd -hashfn=md5
    expose:
      - "8080"
      - "7946"
    ports:
      - "3001:8080"
  flux2:
    build: ./cmd/fluxd
    hostname: flux2
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux3:
    build: ./cmd/fluxd
    hostname: flux3
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux4:
    build: ./cmd/fluxd
    hostname: flux4
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux5:
    build: ./cmd/fluxd
    hostname: flux5
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux6:
    build: ./cmd/fluxd
    hostname: flux6
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux7:
    build: ./cmd/fluxd
    hostname: flux7
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux8:
    build: ./cmd/fluxd
    hostname: flux8
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux9:
    build: ./cmd/fluxd
    hostname: flux9
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  flux10:
    build: ./cmd/fluxd
    hostname: flux10
    entrypoint: fluxd -hashfn=md5 -join=flux1
    expose:
      - "8080"
      - "7946"
    links:
      - flux1
  client:
    build: ./cmd/flux
    entrypoint: flux -server=flux1
    ports:
      - "3000:80"
    links:
      - flux1
  test:
     build: test
     entrypoint: /run.sh http://flux1:8080 0.5
     links:
      - flux1