version: '2'

services:
  node1:
    build: ./cmd/fluxd
    hostname: node1
    entrypoint: fluxd -hashfn=md5
    expose:
      - "8080"
      - "7946"
    ports:
      - "3001:8080"
  node2:
    build: ./cmd/fluxd
    hostname: node2
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node3:
    build: ./cmd/fluxd
    hostname: node3
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node4:
    build: ./cmd/fluxd
    hostname: node4
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node5:
    build: ./cmd/fluxd
    hostname: node5
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node6:
    build: ./cmd/fluxd
    hostname: node6
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node7:
    build: ./cmd/fluxd
    hostname: node7
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node8:
    build: ./cmd/fluxd
    hostname: node8
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node9:
    build: ./cmd/fluxd
    hostname: node9
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  node10:
    build: ./cmd/fluxd
    hostname: node10
    entrypoint: fluxd -hashfn=md5 -join=node1
    expose:
      - "8080"
      - "7946"
    links:
      - node1
  client:
    build: ./cmd/flux
    entrypoint: flux -server=flux1
    ports:
      - "3000:80"
    links:
      - flux1
  test:
     build: test
     entrypoint: /run.sh http://flux1:8080 0.5
     links:
      - flux1