#!/bin/bash


FILENAME="${1##*/}"
BODY=$(curl -s $1)


echo "$BODY"

cat > "$FILENAME.go" << EOF
// generated by embed.sh

package main

import (
    "fmt"
    "net/http"
)

func init() {
    body := \`$(BODY/`/`+"`"+`/)\`

    http.HandleFunc("/$FILENAME", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/json")
        fmt.Fprintf(w, body)
    })
}
EOF